adf

diff --git a/.github/workflows/Matrix and Conditionals.yaml b/.github/workflows/Matrix and Conditionals.yaml
--- a/.github/workflows/Matrix and Conditionals.yaml
+++ b/.github/workflows/Matrix and Conditionals.yaml
@@ -28,9 +28,9 @@ jobs:
         if: ${{! (matrix.number == 2 && matrix.letter == 'c')}}
         run: echo "✅ This step runs for ${{ matrix.number }}-${{ matrix.letter }}"
 
-      - name: Force failure
-        if: ${{ matrix.number == 2 && matrix.letter == 'b'}}
-        run: exit 1
+      # - name: Force failure
+      #   if: ${{ matrix.number == 2 && matrix.letter == 'b'}}
+      #   run: exit 1
 
   
   sleep-job:
